export const AccessRegistryAbi = [
  [
    {
      inputs: [{ internalType: "address", name: "admin", type: "address" }],
      stateMutability: "nonpayable",
      type: "constructor",
    },
    { inputs: [], name: "AccessControlBadConfirmation", type: "error" },
    {
      inputs: [
        { internalType: "address", name: "account", type: "address" },
        { internalType: "bytes32", name: "neededRole", type: "bytes32" },
      ],
      name: "AccessControlUnauthorizedAccount",
      type: "error",
    },
    {
      inputs: [{ internalType: "address", name: "collector", type: "address" }],
      name: "AccessRegistry__AlreadyBlacklisted",
      type: "error",
    },
    {
      inputs: [{ internalType: "address", name: "collector", type: "address" }],
      name: "AccessRegistry__AlreadyRegistered",
      type: "error",
    },
    {
      inputs: [{ internalType: "address", name: "collector", type: "address" }],
      name: "AccessRegistry__Blacklisted",
      type: "error",
    },
    { inputs: [], name: "AccessRegistry__EmptyURI", type: "error" },
    {
      inputs: [{ internalType: "address", name: "collector", type: "address" }],
      name: "AccessRegistry__ProfileNotFound",
      type: "error",
    },
    { inputs: [], name: "AccessRegistry__Unauthorized", type: "error" },
    { inputs: [], name: "AccessRegistry__ZeroAddress", type: "error" },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: "address",
          name: "collector",
          type: "address",
        },
      ],
      name: "CollectorBlacklisted",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: "address",
          name: "collector",
          type: "address",
        },
        {
          indexed: false,
          internalType: "string",
          name: "newProfileURI",
          type: "string",
        },
      ],
      name: "CollectorProfileUpdated",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: "address",
          name: "collector",
          type: "address",
        },
        {
          indexed: false,
          internalType: "string",
          name: "profileURI",
          type: "string",
        },
      ],
      name: "CollectorRegistered",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: "address",
          name: "collector",
          type: "address",
        },
        {
          indexed: false,
          internalType: "uint256",
          name: "totalProjects",
          type: "uint256",
        },
        {
          indexed: false,
          internalType: "uint256",
          name: "completedProjects",
          type: "uint256",
        },
        {
          indexed: false,
          internalType: "uint256",
          name: "defaultedProjects",
          type: "uint256",
        },
      ],
      name: "CollectorReputationUpdated",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: "bytes32",
          name: "role",
          type: "bytes32",
        },
        {
          indexed: true,
          internalType: "bytes32",
          name: "previousAdminRole",
          type: "bytes32",
        },
        {
          indexed: true,
          internalType: "bytes32",
          name: "newAdminRole",
          type: "bytes32",
        },
      ],
      name: "RoleAdminChanged",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: "bytes32",
          name: "role",
          type: "bytes32",
        },
        {
          indexed: true,
          internalType: "address",
          name: "account",
          type: "address",
        },
        {
          indexed: true,
          internalType: "address",
          name: "sender",
          type: "address",
        },
      ],
      name: "RoleGranted",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: "bytes32",
          name: "role",
          type: "bytes32",
        },
        {
          indexed: true,
          internalType: "address",
          name: "account",
          type: "address",
        },
        {
          indexed: true,
          internalType: "address",
          name: "sender",
          type: "address",
        },
      ],
      name: "RoleRevoked",
      type: "event",
    },
    {
      inputs: [],
      name: "DEFAULT_ADMIN_ROLE",
      outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "KYC_ADMIN_ROLE",
      outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "OPERATOR_ROLE",
      outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "POOL_ROLE",
      outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "baseProfileURI",
      outputs: [{ internalType: "string", name: "", type: "string" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "collector", type: "address" }],
      name: "blacklistCollector",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "", type: "address" }],
      name: "collectorProfiles",
      outputs: [
        { internalType: "string", name: "profileURI", type: "string" },
        { internalType: "uint256", name: "totalProjects", type: "uint256" },
        { internalType: "uint256", name: "completedProjects", type: "uint256" },
        { internalType: "uint256", name: "defaultedProjects", type: "uint256" },
        { internalType: "uint256", name: "registeredAt", type: "uint256" },
        { internalType: "bool", name: "exists", type: "bool" },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "collector", type: "address" }],
      name: "getCollectorProfile",
      outputs: [
        {
          components: [
            { internalType: "string", name: "profileURI", type: "string" },
            { internalType: "uint256", name: "totalProjects", type: "uint256" },
            {
              internalType: "uint256",
              name: "completedProjects",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "defaultedProjects",
              type: "uint256",
            },
            { internalType: "uint256", name: "registeredAt", type: "uint256" },
            { internalType: "bool", name: "exists", type: "bool" },
          ],
          internalType: "struct IAccessRegistry.CollectorProfile",
          name: "",
          type: "tuple",
        },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "bytes32", name: "role", type: "bytes32" }],
      name: "getRoleAdmin",
      outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "bytes32", name: "role", type: "bytes32" },
        { internalType: "address", name: "account", type: "address" },
      ],
      name: "grantRole",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "bytes32", name: "role", type: "bytes32" },
        { internalType: "address", name: "account", type: "address" },
      ],
      name: "hasRole",
      outputs: [{ internalType: "bool", name: "", type: "bool" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "collector", type: "address" }],
      name: "incrementCompletedCount",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "collector", type: "address" }],
      name: "incrementDefaultedCount",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "collector", type: "address" }],
      name: "incrementProjectCount",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "", type: "address" }],
      name: "isBlacklisted",
      outputs: [{ internalType: "bool", name: "", type: "bool" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "collector", type: "address" }],
      name: "isEligibleCollector",
      outputs: [{ internalType: "bool", name: "eligible", type: "bool" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "collector", type: "address" }],
      name: "isRegisteredCollector",
      outputs: [{ internalType: "bool", name: "", type: "bool" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "string", name: "cid", type: "string" }],
      name: "registerCollector",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "bytes32", name: "role", type: "bytes32" },
        {
          internalType: "address",
          name: "callerConfirmation",
          type: "address",
        },
      ],
      name: "renounceRole",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "bytes32", name: "role", type: "bytes32" },
        { internalType: "address", name: "account", type: "address" },
      ],
      name: "revokeRole",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "string", name: "newBaseURI", type: "string" }],
      name: "setBaseProfileURI",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "bytes4", name: "interfaceId", type: "bytes4" }],
      name: "supportsInterface",
      outputs: [{ internalType: "bool", name: "", type: "bool" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "string", name: "newCid", type: "string" }],
      name: "updateCollectorProfile",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
  ],
] as const;
